import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./globals.css";
import { MenuButton } from "@/components/menu-button";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { Toaster } from "react-hot-toast";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body 
      // className={inter.className}
      >
        <AppRouterCacheProvider options={{ key: 'css' }}>
        <Toaster
              position="top-center"
              reverseOrder={false}
            />
          <Navbar />
          {children}
          <Footer />
          {/* <MenuButton /> */}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
